name: Build and deploy container app to Azure Web App - chickenapp369

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Change directory
      run: cd ./Chicken_disease_project

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://chickenapp369.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_00dbd09d8c7649f0806afd2c73cd9c4a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_41c1c22448bd4107ae10379abae88ece }}
       
    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: chickenapp369.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_00dbd09d8c7649f0806afd2c73cd9c4a }}/chicken:${{ github.sha }}
        file: Chicken_disease_project/Dockerfile
       
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Change directory
      run: cd Chicken_disease_project
    
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'chickenapp369'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_19d12da230ce4fa499cbbffd03620f96 }}
        images: 'chickenapp369.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_00dbd09d8c7649f0806afd2c73cd9c4a }}/chicken:${{ github.sha }}'
        path: Chicken_disease_project  # Specify the subfolder
